version: '3'
services:
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=storyboard
      - MYSQL_ROOT_PASSWORD=insecure
    volumes:
      - "./mysql:/var/lib/mysql"
  swift:
    image: "bouncestorage/swift-aio"
    ports:
      - "8888:8080"
    volumes:
      - "./swift:/swift/nodes"
